version: '3.8'

services:
  app:  
    build: .
    image: rec-app:latest  
    container_name: library-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:17
    container_name: library-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: